apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
stringData:
  connectionString: {{ .Values.secrets.connectionString | quote }}
  jwtSecret: {{ .Values.secrets.jwtSecret | quote }}
  stripeSecretKey: {{ .Values.secrets.stripeSecretKey | quote }}
  stripeWebhookSecret: {{ .Values.secrets.stripeWebhookSecret | quote }}
  ownerEmail: {{ .Values.secrets.ownerEmail | quote }}
  ownerPassword: {{ .Values.secrets.ownerPassword | quote }}
{{- if .Values.secrets.redisConnectionString }}
  redisConnectionString: {{ .Values.secrets.redisConnectionString | quote }}
{{- end }}
